name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

# First build and test with JDK 11
# Then run tests with JDK 8, 17, and 21
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        id: gradle-build
        run: ./gradlew --no-daemon :build-logic:build build --stacktrace

      - name: Store reports
        if: always() && (steps.gradle-build.outcome == 'success' || steps.gradle-build.outcome == 'failure')
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/

  test-jdk:
    needs: linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 17, 21 ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: |
            ${{ matrix.java }}
            11

      - name: Setup environment
        run: |
          echo "org.gradle.java.installations.auto-download=false" | tee -a gradle.properties
          echo "org.gradle.java.installations.fromEnv=JAVA_HOME_${{ matrix.java }}_X64" | tee -a gradle.properties

      - uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        id: gradle-build
        run: ./gradlew --no-daemon test "-Ptest.java-toolchain=${{ matrix.java }}"

      - name: Store reports
        if: always() && (steps.gradle-build.outcome == 'success' || steps.gradle-build.outcome == 'failure')
        uses: actions/upload-artifact@v3
        with:
          name: jdk-${{ matrix.java }}-tests
          path: |
            **/build/reports/tests/test/
            **/build/test-results/
